//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiemOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class score
    {
        public int id_score { get; set; }
        public int id_student { get; set; }
        public int test_code { get; set; }
        public Nullable<System.DateTime> time_finish { get; set; }
        public double score_number { get; set; }
        public string detail { get; set; }
    
        public virtual student student { get; set; }
        public virtual test test { get; set; }
    }
}
